export const CART_ACTION_TYPES = {
    "TOGGLE_CART": "cart/SET_IS_CART_OPEN",
    "SET_CART_ITEMS": "cart/SET_CART_ITEMS",
    "SET_CART_QUANTITY": "cart/SET_CART_QUANTITY",
    "SET_CART_TOTAL": "cart/SET_CART_TOTAL"
}